services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/portfolio-api/bin/migrate up && /portfolio-api/bin/api" ]
    restart: always

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=portfolio-api_db
      - POSTGRES_USER=portfolio-api_user
      - POSTGRES_PASSWORD=portfolio-api_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U portfolio-api_user -d portfolio-api_db" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always