basePath: /v1
definitions:
  err.Error:
    properties:
      error:
        type: string
    type: object
  err.Errors:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
  post.DTO:
    properties:
      description:
        type: string
      email:
        type: string
      id:
        type: string
      message:
        type: string
      name:
        type: string
      subject:
        $ref: '#/definitions/post.PostSubject'
    type: object
  post.Form:
    properties:
      description:
        type: string
      email:
        type: string
      message:
        type: string
      name:
        type: string
      subject:
        type: string
    type: object
  post.PostSubject:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - Choose
    - Feedback
    - Report
    - Other
host: localhost:8080
info:
  contact: {}
  description: This is a sample RESTful API with a CRUD
  license:
    name: MIT License
  title: PORTFOLIO API
  version: "1.0"
paths:
  /../health:
    get:
      description: Read health
      responses:
        "200":
          description: OK
      summary: Read health
      tags:
      - health
  /post:
    post:
      consumes:
      - application/json
      description: Create post
      parameters:
      - description: Post form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/post.Form'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Create post
      tags:
      - post
  /post/{id}:
    delete:
      consumes:
      - application/json
      description: Delete post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Delete post
      tags:
      - post
    get:
      consumes:
      - application/json
      description: Read post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post.DTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Read post
      tags:
      - post
    put:
      consumes:
      - application/json
      description: Update post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      - description: Post form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/post.Form'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Update post
      tags:
      - post
  /posts:
    get:
      consumes:
      - application/json
      description: List posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/post.DTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: List posts
      tags:
      - posts
swagger: "2.0"
